let datum = {
    nodes: [
        {"name": "A", "age": "1"},
        {"name": "B", "age": "2"},
        {"name": "C", "age": "3"},
        {"name": "D", "age": "4"},
        {"name": "E", "age": "5"},
        {"name": "F", "age": "6"},
        {"name": "G", "age": "7"},
        {"name": "H", "age": "8"},
        {"name": "I", "age": "9"},
        {"name": "J", "age": "10"},
        {"name": "K", "age": "11"},
        {"name": "L", "age": "12"},
        {"name": "M", "age": "13"},
        {"name": "N", "age": "14"},
        {"name": "O", "age": "15"},
        {"name": "P", "age": "16"},
        {"name": "Q", "age": "17"},
        {"name": "R", "age": "18"},
        {"name": "S", "age": "19"},
        {"name": "T", "age": "20"},
        {"name": "U", "age": "21"},
        {"name": "V", "age": "22"},
        {"name": "W", "age": "23"},
        {"name": "X", "age": "24"},
        {"name": "Y", "age": "25"},
        {"name": "Z", "age": "26"},
        {"name": "AA", "age": "27"}
    ],
    edges: [
        {"source": "C", "target": "B" },
        {"source": "C", "target": "A" },
        {"source": "C", "target": "D" },
        {"source": "C", "target": "F" },
        {"source": "C", "target": "G" },
        {"source": "C", "target": "E" },
        {"source": "E", "target": "B" },
        {"source": "D", "target": "A" },
        {"source": "H", "target": "D" },
        {"source": "I", "target": "F" },
        {"source": "B", "target": "G" },
        {"source": "C", "target": "L" },
        {"source": "L", "target": "K" },
        {"source": "L", "target": "Q" },
        {"source": "L", "target": "P" },
        {"source": "P", "target": "Q" },
        {"source": "O", "target": "M" },
        {"source": "M", "target": "B" },
        {"source": "M", "target": "C" },
        {"source": "N", "target": "M" },
        {"source": "N", "target": "C" },
        {"source": "J", "target": "C" },
        {"source": "Q", "target": "C" },
        {"source": "Q", "target": "F" },
        {"source": "K", "target": "G" },
        {"source": "M", "target": "V" },
        {"source": "R", "target": "V" },
        {"source": "U", "target": "R" },
        {"source": "N", "target": "T" },
        {"source": "J", "target": "U" },
        {"source": "Q", "target": "T" },
        {"source": "U", "target": "F" },
        {"source": "U", "target": "S" },
        {"source": "X", "target": "Z" },
        {"source": "Z", "target": "V" },
        {"source": "U", "target": "R" },
        {"source": "Y", "target": "X" },
        {"source": "C", "target": "U" },
        {"source": "W", "target": "Y" },
        {"source": "X", "target": "B" },
        {"source": "U", "target": "AA"}
    ]
}

export { datum }